### ISSUE TITLE
Run SVGO on SVGs in a Pull Request

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#13]
- [x] Get a list of files in the Pull Request (0c273b014837fb9a825e901c2180a126eb7fd9c5)
- [x] Filter out all non-SVG files in the Pull Request (#11)
- [x] Get the contents of the SVG files (#11)
- [x] Decode file (#19)
- [x] Run SVGO on the (decoded) SVGs (#26)
- [x] Commit SVG files back (#39)
