### ISSUE TITLE
Add support for configuration

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#17]
Add functionality that allows users to customize how the action works. Some ideas for options:

- [x] Specify the path of the SVGO configuration file (e.g. if it has a non-standard name) (#43)
- [x] Configure commit title/message of the commit created by the action (#42)
- [x] Automatically use semantic commit title (#96)
- [x] Dry run (#41)
- [x] Option for a comment with a summary of the optimization (#70)
- [x] Specify glob for files that should be ignored (#162)
- [ ] Specify glob for files that should be consider - ignoring all others (?)
- [x] Configure the bot comment (#174)
- [x] Remove [notice about this issue in the README](https://github.com/ericcornelissen/svgo-action/blob/develop/README.md#configure-the-action) (63344194b9ada8c204fc5274f1652050d1900039)

Other suggestions for configuration options are welcome. You can suggest them as a comment here or open a separate issue 🙂

**Comment by ericcornelissen** [comment]
Closing this for now, with "Specify glob for files that should be consider - ignoring all others (?)" still open.

If there is anyone that would like to see that option being added, feel free to comment here or just [open a new issue](https://github.com/ericcornelissen/svgo-action/issues/new) 🙂
