### ISSUE TITLE
Setup code coverage

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#44]
- [x] Get code coverage report from Jest, e.g.: `$ npm run test:coverage` (#46)
- [x] Set up code coverage reports integration, e.g.: [Codecov.io](https://codecov.io/) (#65)
  - [x] Add badge to README (e5939c8250be609a2cb71782cfb0beb04b63aea8)
