### ISSUE TITLE
Add deprecation warning when using SVGO v1

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#467]
# Feature Request

- **SVGO Action version**: [v1.3.10](https://github.com/ericcornelissen/svgo-action/releases/tag/v1.3.10) _and_ [v2.1.1](https://github.com/ericcornelissen/svgo-action/releases/tag/v2.1.1)

- **On**: _any_

## Description

SVGO v1 was recently deprecated, this Action should reflect that when SVGO v1 is used by the user as they may otherwise miss the deprecation warning.

### Example

With the configuration

```yaml
with:
  svgo-version: 1
```

There should be an [annotation](https://github.com/actions/toolkit/tree/6ce349e08cc692c789ab21189a31f687dc8a1cf8/packages/core#annotations) outputted in GitHub Actions that says something similar to:

```
npm WARN deprecated svgo@1.0.0: This SVGO version is no longer supported. Upgrade to v2.x.x.
```

Which is the deprecation warning you get when you execute, e.g.:

```bash
$ npm install svgo@v1.0.0
```

## Proposal

Add a `notice` or `warning` annotation with the text similar to the example. Both annotation levels seem sensible; `notice` is the level of obtrusiveness I would expect, but the npm output is a `warning` (though it should be noted that the npm CLI has more levels to choose from).

## Progress

_Leave a comment if you want to work on any of the open items_

- [x] Add annotation to Action v1 (#469)
- [x] Add annotation to Action v2 (#466)
- [x] Update Action v1 docs (#469)
- [x] Update Action v2 docs (#466)
