### ISSUE TITLE
Management of non-package registry dependencies

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#711]
Many of this project's runtime and development dependencies[^1] are explicitly tracked (in [`package-lock.json`](https://github.com/ericcornelissen/svgo-action/blob/0c572b411371c3c6596909225caef0abe5a1e9d4/package-lock.json) or [GitHub Actions workflows](https://github.com/ericcornelissen/svgo-action/tree/0c572b411371c3c6596909225caef0abe5a1e9d4/.github/workflows)), some system-level development dependencies aren't explicitly tracked but this is considered fine[^2] (git, Node.js, npm, act, Docker, EditorConfig), but some development dependencies aren't explicitly tracked and/or kept up-to-date but ideally are. This issue is about that last category.

> **Note**: Feel free to comment on this issue if you think this list is incomplete or if you have any suggestions for improvements.

### Overview

- [x] [cosign](https://github.com/ericcornelissen/svgo-action/blob/417154a9fa43c6960640bb4df7ddcfd066ff16d8/.github/workflows/publish.yml#L105): ~~ideally kept up-to-date.~~
  - Tracking added in #740
  - Updating added in #741
- [x] [actionlint](https://github.com/ericcornelissen/svgo-action/blob/0c572b411371c3c6596909225caef0abe5a1e9d4/CONTRIBUTING.md?plain=1#L103): ~~ideally tracked & kept up-to-date.~~
  - Tracking added in #720
  - Updating added in #741
- [x] [CodeQL packs](https://github.com/ericcornelissen/svgo-action/blob/0336ba4e88a859e293558ca129e7e5761960fce4/.github/codeql-config.yml#L5-L6): See #553
- [x] [hadolint](https://github.com/ericcornelissen/svgo-action/blob/0c572b411371c3c6596909225caef0abe5a1e9d4/CONTRIBUTING.md?plain=1#L156) ideally kept up-to-date.
  - Tracking added in #745
  - Updating added in #745
- [x] [ShellCheck](https://github.com/ericcornelissen/svgo-action/blob/0c572b411371c3c6596909225caef0abe5a1e9d4/CONTRIBUTING.md?plain=1#L104): ~~ideally tracked & kept up-to-date.~~
  - Tracking added in #720
  - Updating added in #741

[^1]: I'm considering the [devcontainer configuration](https://github.com/ericcornelissen/svgo-action/tree/0c572b411371c3c6596909225caef0abe5a1e9d4/.devcontainer) out of scope for this issue.
[^2]: If known, these should have a minimum required version specified to make contributing easier
