### ISSUE TITLE
Configuration validation tool

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#94]
As mentioned already in #71, it would be cool to have a tool that can verify the configuration of the action before you use it.

Features:

- [x] Errors, Warning, and Suggestions for both Workflow file configuration and config files (#163)
- [x] Show an example commit for the configuration (#163)
- [x] Show an example comment for the configuration (#163)
- [ ] Check templates for unknown values
- [ ] Check if the commit title is too long (with templating values removed/replaced)
- [ ] Check if `on:` values in a Workflow file are supported

**Comment by ericcornelissen** [comment]
Closing this as this is not relevant to v2, there is far less configuration available and GitHub does a decent job of informing you when your configuration is invalid. I also **will not** consider this issue for v1.
